[package]
name = "zkreserves_circuit"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]
name = "zkreserves"
function = "zkreserves_circuit::main::main"

[lib]

[dependencies]
cairo_execute = "2.16.0"

[cairo]
enable-gas = false
